apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: clusterrolebinding 
subjects: 
- kind: User 
  name: eks-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: fullaccess
  apiGroup: rbac.authorization.k8s.io
