apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb-deployment
  namespace: prod
  labels:
    app: mongodb
spec: 
  replicas: 1 ### note we must run db pods only 1 is recommened
  strategy:
    type: RollingUpdate
  selector: 
    matchLabels:
      app: mongodb
  template: 
    metadata: 
      labels: 
        app: mongodb 
    spec: 
      containers: 
      - name: mongodb
        image: mongo 
        ports: 
        - containerPort: 27017
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          value: bittu
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: bittu@123
        volumeMounts: 
        - name: mongobittu
          mountPath: /data/db 
      volumes: 
      - name: mongobittu
        nfs: 
          server: 172.31.44.185  # Replace with your NFS server IP or hostname
          path: /mongo/bittu 
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
