apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-for-eks-user
  namespace: prod
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "update"]
