apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
  namespace: prod
spec: 
  type: NodePort
  selector: 
    app: nginx 
    version: 1.0.0
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 30080 
