
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginxdeployment
  namespace: prod
  labels:
    app: nginx 
    version: 1.0.0
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: nginx 
      version: 1.0.0
  template: 
    metadata:
      labels:
        app: nginx 
        version: 1.0.0
    spec: 
      containers: 
      - name: nginx 
        image: nginx:latest
        ports: 
        - containerPort: 80
